import importlib, os, sys
"""
Install requirements for Agdas.
"""

# path of agdas project
script_path = os.path.dirname(os.path.realpath(__file__))

class Install:
    """
    Install all dependencies of pyAgdas.
    """

    def __init__(self):
        """
        Use pipreqs to install dependencies from requirements.txt. The file is automatically generated by the pipreqs library.
        """
        ins = False
        # open requirements
        with open('requirements.txt', 'r') as f:

            for l in f.read().splitlines():
                library = l.split('=')[0]

                try:
                    importlib.import_module(library)

                except ModuleNotFoundError:
                    ins = True

        if ins:
            os.system('{} -m pip install --upgrade pip'.format(sys.executable))
            os.system('{} -m pip install pipreqs'.format(sys.executable))
            os.system('{} -m pipreqs.pipreqs {} --encoding utf-8-sig --force'.format(sys.executable, script_path))
            os.system('{} -m pip install -r requirements.txt'.format(sys.executable))

if __name__ == "__main__":
    Install()